imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false
    csrf_protection: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        path: /tmp/janus_test

# Note: these are cache providers provided by, but not for, Doctrine.
doctrine_cache: null