# @todo create parameters file from janus config using a file cache proxy
# @todo set auto create proxies based on janus doctrine.proxy_auto_generate config
parameters:
    # Note that memcache connection info (for multiple servers is provided by Janus SimpleSamlIntegration Bundle
    # In the form of memcache.server_groups.{servergroup nr}.{server nr}.

    admin_email: null
    admin_name: admin
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: janus
    security.authentication.manager.erase_credentials: false
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: janus_db
    database_user: janus
    database_password: janus_password
    database_prefix: janus__
